all:
  hosts:
    bigbrother.clickdefense.in:
      ansible_host: 192.168.1.100
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/bigbrother.clickdefense.in/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

