all:
  vars: 
    ansible_user_name: ansible_user
    ansible_bastion_pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG3pJ+GwpR5zFldXDA/X7aqp6JrFeTeCdRaSx718vGEX oscar@latubu
    ansible_user_password: "$6$k.yWfWEewhNEtudw$Bp1saLt2nF.LZ7TmIbj9SUJL.SZQJMfbdAvTKboILs/AdTLGd1JvU1j8PjhjjGd4Ypm4KRuS6u/WH4q8vmJCi0"
    ansible_user_authorized_keys: "{{ ansible_bastion_pubkey }}"

  hosts:

    bigbrother.clickdefense.in:
      ansible_host: 192.168.1.100
      ansible_user: ansible_user
      container_user: ansible_user
      ansible_become: true

