---
- name: Setup Rsyslog Docker Container on Debian
  hosts: all
  become: true

  vars:
    rsyslog_dir: "/home/{{ container_user }}/services/rsyslog"
    docker_compose_file: "{{ rsyslog_dir }}/docker-compose.yml"
    rsyslog_conf_file: "{{ rsyslog_dir }}/rsyslog.conf"

  tasks:

    - name: Ensure '{{ container_user }}' exists before proceeding
      ansible.builtin.getent:
        database: passwd
        key: "{{ container_user }}"
        fail_key: true

    - name: Install required APT packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - vim
          - tmux
          - bc
          - tcpdump
          - snmp
        update_cache: yes
        state: present

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository (bookworm)
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker

    - name: Install Docker and Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create rsyslog service directory
      file:
        path: "{{ rsyslog_dir }}"
        state: directory
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0755'
        recurse: yes

    - name: Template docker-compose.yml
      template:
        src: rsyslog/docker-compose.yml.j2
        dest: "{{ docker_compose_file }}"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0644'

    - name: Template rsyslog.conf
      template:
        src: rsyslog/rsyslog.conf.j2
        dest: "{{ rsyslog_conf_file }}"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0644'

    - name: Ensure rsyslog.d directory exists
      file:
        path: "{{ rsyslog_dir }}/rsyslog.d"
        state: directory
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0755'

    - name: Start rsyslog container as {{ container_user }}
      shell: "sudo -u {{ container_user }} docker compose -f {{ docker_compose_file }} up -d"
      args:
        chdir: "{{ rsyslog_dir }}"

