---
- name: Configure rsyslog client to forward logs to central server
  hosts: all
  become: true

  vars:
    rsyslog_server_host: 127.0.0.1        # change to your actual collector IP or hostname
    rsyslog_server_port: 514
    rsyslog_protocol: udp                 # or 'tcp'

  tasks:
    - name: Ensure rsyslog is installed
      apt:
        name: rsyslog
        state: present
        update_cache: yes

    - name: Configure rsyslog forwarding to central server (via template)
      template:
        src: 90-central-logger.conf.j2
        dest: /etc/rsyslog.d/90-central-logger.conf
        mode: '0644'

    - name: Restart rsyslog to apply forwarding configuration
      service:
        name: rsyslog
        state: restarted

