---
- name: Configure rsyslog client to forward logs to central server
  hosts: all
  become: true

  vars:
    rsyslog_server_host: bigbrother.clickdefense.in
    rsyslog_server_port: 514
    rsyslog_protocol: udp  # o "tcp" si prefieres
    client_config_file: /etc/rsyslog.d/90-central-logger.conf

  tasks:
    - name: Install rsyslog (if not already present)
      apt:
        name: rsyslog
        state: present
        update_cache: yes

    - name: Configure rsyslog to forward logs to central server
      copy:
        dest: "{{ client_config_file }}"
        content: |
          *.* @{{ rsyslog_server_host }}:{{ rsyslog_server_port }}
        mode: '0644'

      when: rsyslog_protocol == 'udp'

    - name: Configure rsyslog to forward logs to central server (TCP)
      copy:
        dest: "{{ client_config_file }}"
        content: |
          *.* @@{{ rsyslog_server_host }}:{{ rsyslog_server_port }}
        mode: '0644'
      when: rsyslog_protocol == 'tcp'

    - name: Restart rsyslog to apply changes
      service:
        name: rsyslog
        state: restarted

