---
- name: Setup SNMP Server Container on Debian
  hosts: all
  become: true

  tasks:

    - name: Ensure '{{ container_user }}' exists before proceeding
      ansible.builtin.getent:
        database: passwd
        key: "{{ container_user }}"
        fail_key: true
      register: container_user_check

    - name: Install required APT packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - vim
          - tmux
          - bc
          - tcpdump
          - snmp
        update_cache: yes
        state: present

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository (bookworm)
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker

    - name: Install Docker and Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create SNMP service directory
      file:
        path: "{{ snmp_dir }}"
        state: directory
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0755'
        recurse: yes

    - name: Template docker-compose.yml
      template:
        src: templates/snmpd/docker-compose.yml.j2
        dest: "{{ snmp_dir }}/docker-compose.yml"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0644'

    - name: Template snmpd.conf
      template:
        src: templates/snmpd/snmp.conf.j2
        dest: "{{ snmp_conf_file }}"
        owner: "{{ container_user }}"
        group: "{{ container_user }}"
        mode: '0644'

    - name: Start snmpd container as {{ container_user }}
      shell: "sudo -u {{ container_user }} docker compose -f {{ snmp_docker_compose_file }} up -d --build --force-recreate"
      args:
        chdir: "{{ snmp_dir }}"
